version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mictouikit.rule=Host(`ui.apps.misangono.net`)"
      - "traefik.http.routers.mictouikit.entrypoints=websecure"
      - "traefik.http.routers.mictouikit.tls=true"
      - "traefik.http.services.mictouikit.loadbalancer.server.port=3000"

    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
